
COPY staging_consolidado_despesas (
    data,
    regans,
    cdcontacontabil,
    descricaogastos,
    vlsaldoinicial,
    vlsaldofinal,
    valordespesas,
    valorsuspeito,
    ano,
    trimestre,
    cnpj,
    razaosocial,
    nomefantasia,
    modalidade,
    logradouro,
    numero,
    complemento,
    bairro,
    cidade,
    uf,
    cep,
    ddd,
    telefone,
    fax,
    enderecoeletronico,
    representante,
    cargorepresentante,
    regiaocomercializacao,
    dataregistroans,
    cnpjinvalido
    )
    --ALTERE O DIRETORIO PARA CRIAR A TABELA
FROM '...\Pasta-Raiz-Projeto\Trimestres\consolidado_despesas.csv'
DELIMITER ';'
CSV HEADER
ENCODING 'UTF8';


INSERT INTO consolidado_despesas (
    data,
    reg_ans,
    cd_conta_contabil,
    descricao_gastos,
    vl_saldo_inicial,
    vl_saldo_final,
    valor_despesas,
    valor_suspeito,
    ano,
    trimestre,
    cnpj,
    razao_social,
    nome_fantasia,
    modalidade,
    logradouro,
    numero,
    complemento,
    bairro,
    cidade,
    uf,
    cep,
    ddd,
    telefone,
    fax,
    endereco_eletronico,
    representante,
    cargo_representante,
    regiao_comercializacao,
    data_registro_ans,
    cnpj_invalido
)
SELECT
    cast(data AS date),
    regans,
    cdcontacontabil,
    descricaogastos,
    vlsaldoinicial,
    vlsaldofinal,
    valordespesas,
    valorsuspeito,
    ano,
    trimestre,
    cnpj,
    razaosocial,
    nomefantasia,
    modalidade,
    logradouro,
    numero,
    complemento,
    bairro,
    cidade,
    uf,
    cep,
    ddd,
    telefone,
    fax,
    enderecoeletronico,
    representante,
    cargorepresentante,
    cast(regiaocomercializacao AS VARCHAR(15)),
    cast(dataregistroans AS date),
    cnpjinvalido
FROM staging_consolidado_despesas;
